name: dchs_flutter_compass
description: A Flutter compass. The heading varies from 0-360, 0 being north.
version: 1.0.0
homepage: https://github.com/dariocavada/dchs_flutter_compass

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dariocavada.dchsfluttercompass
        pluginClass: DchsFlutterCompassPlugin
      ios:
        pluginClass: DchsFlutterCompassPlugin
